swagger: "2.0"
info:
  description: "this service is for interpolating in time series, type in input json can be 'shamsi' or 'miladi' time in json can be 'daily', 'monthly', 'hourly', 'minutes' and 'seconds' and in the input json interpolation method can be 'linear' or 'polynomial' or 'spline' in config section we have tool option this option can be 'Pandas' or 'Dask' if you select Pandas program will run with pandas and in Dask mode program use Dask package"
  version: "1.0.0"
  title: "service1 API"
paths:
  /:
    post:
      tags:
      - "is API active?"
      summary: "just for seeing our API is active or not"
      description: ""
      responses:
        "200":
          description: "API is active and is ready to use"
        "405":
          description: "API is not active"
  /service1:
    post:
      tags:
        - "service1"
      summary: "interplate in time series"
      description: "time most be one of 'daily', 'monthly', 'hourly', 'seconds', 'minutes'\n
                    type most be one of 'shamsi', 'miladi\n
                    interpolation most be one of 'linear', 'polynomial', 'spline'\n
                    miladi times must be in integer foramt and shamsi times must be in '1399-12-12 15:16:17.101' shape and having string format\n
                    tool can be 'Pandas' or 'Dask'"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "input json"
          required: true
          schema:
            $ref: "#/definitions/service1"
      responses:
        "200":
          description: "congratulations in output json we dont ave config section and you just have data section with time and vol options"
        "405":
          description: "Something is wrong"
definitions:
  service1:
    example:
      "{
         \"data\": {
           \"time\": {
             \"0\": 1577836800000,
             \"1\": 1577923200000,
             \"2\": 1578096000000
          },
           \"vol\": {
             \"0\": 20,
             \"1\": 40,
             \"2\": 100
          }
        },
         \"config\": {
           \"type\": \"miladi\",
           \"time\": \"daily\",
           \"interpolation\": \"linear\",
           \"tool\":\"Dask\"
        }
      }"